import { BlogMeta } from '@/utils/interface'
import Link from 'next/link'
import React from 'react'
import { getAllBlogs } from '../api/api'
import Head from 'next/head'

interface BlogsPageProps {
  blogs: BlogMeta[]
}

export default function BlogsPage({blogs}:BlogsPageProps) {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container max-w-3xl'>
        <h1 className='text-3xl font-bold'>Blog</h1>
        <ul className='mt-2 flex flex-col gap-4'>
          {blogs.map((blog: BlogMeta, index: number) => {
            return <li key={index}>
              <Link href={`/blog/${blog.slug}`} className='font-medium  text-md'>
                {blog.title}
              <p className='text-xs font-extralight ml-2'>
                {blog.excerpt}
              </p> 
              <ul className='flex gap-2 text-xs mt-2 ml-1'>
                {blog.tags.map((tag: string, index: number) => {
                  return <li key={index} className='px-2 py-1 bg-slate-100 rounded-sm'>
                      {tag}
                    </li>
                })}
              </ul>
              </Link>
            </li>
          })}
        </ul>
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const blogs = getAllBlogs().slice(0, 9).map(blog => blog.meta)
  return {
    props: {
      blogs: blogs
    }
  }
}